### ISSUE TITLE
Expo Go

### ISSUE THREAD

**Issue by brunoreale** [expo-community/expo-firebase-starter#37]
I found [this ](https://levelup.gitconnected.com/how-to-use-the-react-context-api-to-build-react-native-expo-and-firebase-apps-adda840e52b0), installed on my machine. I'm not using AndroidStudio, only Expo CLI/GO and can't have success running the project. 
I'm using Windows 7, 32-bits, Node 12.8.3, Expo 4.2.1, Android device 7.1, Expo Go latest (SDK 40.0)
Can you help me? Thanks

```bash
Error: Failed to start watch mode.
    at Timeout._onTimeout (C:\projects\expo\fb-app\node_modules\jest-haste-map\b
uild\index.js:1059:24)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Error: Failed to start watch mode.
    at Timeout._onTimeout (C:\projects\expo\fb-app\node_modules\jest-haste-map\b
uild\index.js:1059:24)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Error: Failed to start watch mode.
    at Timeout._onTimeout (C:\projects\expo\fb-app\node_modules\jest-haste-map\b
uild\index.js:1059:24)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Error: Failed to start watch mode.
    at Timeout._onTimeout (C:\projects\expo\fb-app\node_modules\jest-haste-map\b
uild\index.js:1059:24)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
- Stopping server(node:8232) UnhandledPromiseRejectionWarning: Error: Failed to
start watch mode.
    at Timeout._onTimeout (C:\projects\expo\fb-app\node_modules\jest-haste-map\b
uild\index.js:1059:24)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:8232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 2)
(node:8232) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
› Stopped server

C:\projects\expo\fb-app>

**Comment by nileshsarode** [comment]
Same problem with me, I am trying to install with expo and trying to run on browser.
Thanks.

**Comment by brunoreale** [comment]
> Same problem with me, I am trying to install with expo and trying to run on browser.
> Thanks.

I guess is the [same](https://github.com/expo-community/expo-firebase-starter/issues/30#issue-761346950)

**Comment by amandeepmittal** [comment]
Are you both still facing this issue? Let me try to reproduce it on my own end.

Meanwhile, could be a [watchman issue](https://forums.expo.io/t/failed-to-construct-transformer-error-failed-to-start-watch-mode/35731) too.
